### ISSUE TITLE
Question: How to structure complex, linear integration tests

### ISSUE THREAD

**Issue by hasryan** [sclevine/spec#10]
I am curious what the ideal way is to structure a complex/long-running integration test with this library. To be specific: I am writing a test (using Agouti) that logs into a web application, interacts with a series of pages in sequence, and then logs out. This is one cohesive, linear test, meaning that each step along the way is interacting with the same browser window and that actions taken early on in the test generate state that is relied upon by actions taken later on in the test.

Originally I attempted to implement this with Ginkgo but found that it did not seem to support this pattern very well because it does not guarantee execution of tests in the order they are defined.  See for more information: https://github.com/onsi/ginkgo/issues/246 . In order to work around this I ended up with a single, long flat spec with a bunch of `ginkgo.By` comments describing the context and actions being taken. When I got to that point I realized I wasn't getting much value out of Ginkgo since it was basically just a long procedural function without any BDD-like structure.

What drew me to this library is that by default it executes specs in sequential order, which solves my problem above. I also like that it has the flexibility for me to run a sub-group of specs in parallel or random order should I explicitly choose to.

I hoped to be able to write tests with more definition than the single flat spec I ended up with in Ginkgo. My plan was to do something like this:

```
// login
when: user navigates to login page
  it: should display the login form
  when: user fills out form and clicks submit
    it: should navigate away from the login page
    it: should load the logged-in section of the application

// create a transaction
when: the user clicks the "New Transaction" button
  it: should display a popup form
  when: user enters the transaction details and submits
    it: should remain on the same page
    it: should display a "success" message at the top
    ... more nested groups of specs ...

... etc ...
```

The problem I ran into is that, as the documentation states, each group function (`when`) is re-executed for each spec inside of it.  So using my login example above, rather than one linear path:

```
navigate to login => see form => fill & submit form => see login page disappear => see logged-in section appear
```

It would instead do:

```
navigate to login => see form
navigate to login => see form => fill & submit form => see login page disappear
navigate to login => see form => fill & submit form => see logged-in section appear
```

The problem is that some of the actions I'll be taking on this path will be creating or mutating data. If each spec effectively terminates after executing it will generate a lot of random data that is difficult to clean up. Also the shared browser will get into a weird state as some specs will give it up after navigating somewhere else, and their sibling specs will have to reset it to its original location or initialize their own browsers.

I may be attempting to shoehorn what actually is just a long, procedural/flat test into this structure when it doesn't fit. Any thoughts on this would be appreciated.

**Comment by sclevine** [comment]
The standard library has [a feature called subtests](https://blog.golang.org/subtests) that provides exactly the behavior you want and integrates cleanly with spec. Spec is really just a wrapper/closure-generator for subtests that provides BDD-style test isolation (which you don’t want in this case). Because subtests are nestable, you should be able to declare subtests inside of any `spec.S` (`it`) block.

Let me know if you run into any trouble with this technique.

**Comment by hasryan** [comment]
Thank you for the suggestion @sclevine that does seem like a reasonable approach. I did start using subtests for the control I require, but didn't consider that I could still utilize spec for individual subtests where it fits well. Thanks for your perspective and for the awesome library!
