### ISSUE TITLE
Example of table-driven tests

### ISSUE THREAD

**Issue by arsham** [sclevine/spec#12]
Hi,

Can you provide the best way of utilising Table-Driven tests with spec please?

Thank you.

**Comment by sclevine** [comment]
Spec is intended for writing BDD-style tests. Spec is not a framework, and it doesn't replace any of the functionality of the standard library `testing` package. You can write table-driven tests [just like you would without spec](https://github.com/golang/go/wiki/TableDrivenTests).

If you'd like, you can write table-driven tests inside of `spec.S` ("it") blocks, or even [include spec blocks inside of your table tests](https://github.com/buildpack/lifecycle/blob/master/acceptance/acceptance_test.go#L26) (just make sure you only iterate over static data).

**Comment by arsham** [comment]
It looks perfect. Thank you.
