### ISSUE TITLE
Feature: Spec Should exit non-zero if test is focused

### ISSUE THREAD

**Issue by zachgersh** [sclevine/spec#16]
So, I mistakenly committed a focus and this is particularly easy to do if you are not running `go test -v` since you'll end up just getting an `ok` as your resulting test output.

Can we design a way here so the tests actually exit non-zero due to the fact that a focus has been left in while still running that focused tests (this is the same sort of guard that ginkgo has).

**Comment by sclevine** [comment]
Spec is not a testing framework. It's just a small library to help you organize subtests à la BDD.

Skipping tests with `t.Skip()` doesn't result in a non-zero exist status, and so that's how focus and pend work.

**Comment by sclevine** [comment]
I ended up adding an option (`spec.FailFocus()`) to allow users to opt-in to the requested behavior.
It's currently available on this branch: https://github.com/sclevine/spec/tree/spec-1.5-rc
