### ISSUE TITLE
Test failure handling in report/terminal.go

### ISSUE THREAD

**Issue by kardolus** [sclevine/spec#5]
Was wondering if [this case](https://github.com/kardolus/spec/blob/b518b20aa1af75d314a31c9b3acfeeab7c4cbfb4/report/terminal.go#L29) is ever executed when a test failure occurs. 

From the few tests I performed with a spec-fork, it seems like there is a panic when a test fails, causing the case never to run, and [the summary](https://github.com/kardolus/spec/blob/b518b20aa1af75d314a31c9b3acfeeab7c4cbfb4/report/terminal.go#L50) to be skipped.

The reason I'm looking into this is because I want to print the failure output in a different color. Sometimes in spec it's hard to see wether there were failing tests. I have been wrapping `go test` in a shell script in order to print a test-status message (failure or success based on exit code). Would be better to change things in spec though. 

No rush at all, playing around with the fork and trying to fix it, but perhaps you have tips/ideas. I was thinking, in case the failures can never actually be counted, we may want to leave the failure count out of the summary and print the number of tests/skipped tests instead.

**Comment by kardolus** [comment]
Thanks @sclevine - All I did was change [this line](https://github.com/cloudfoundry/php-cnb/blob/9077ae94a3f65708451e9c29d1ae894e7086c0af/php/php_test.go#L148) on the `php-cnb` to `Expect(f.Build.Layers).NotTo(test.HaveLaunchMetadata(...`. Just so I had a test failure to play with. 

Will look into rainbow-reporter and Gomega registration.

**Comment by sclevine** [comment]
> Perhaps this (L24) is an incorrect way of registering *testing.T?

Yep, see #4 for more details.
I'd recommend this way, because it will let you run the specs in parallel as well:
```go
func Test(t *testing.T) {
	spec.Run(t, "Example", testFoo, spec.Parallel(), spec.Report(report.Terminal{}))
}

func testFoo(t *testing.T, when spec.G, it spec.S) {
	var g *gomega.WithT
	it.Before(func() { g = NewWithT(t) })

	when("one test passes and one fails", func() {
		it("passes and is shown as a pass", func() {
			g.Expect(foo()).To(Equal(5))
		})

		it("fails and is shown as a pass", func() {
			g.Expect(foo()).To(Equal(6))
		})
	})
}
```
Alternatively, I personally prefer [go-cmp](https://github.com/google/go-cmp) to Gomega.

**Comment by kardolus** [comment]
Thanks! That works. Will look into go-cmp.
