### ISSUE TITLE
Skip packages

### ISSUE THREAD

**Issue by joaopapereira** [sclevine/spec#8]
It would be interesting if we could have a flag that would allow us to skip a package.

Scenario:
 Given we have a folder with acceptance tests, we should be able to run all the tests excluding the acceptance test:
`go test -v -skipPackage=acceptance`

If the flag could do partial check it would be a plus.
`go test -v -skipPackage=acc`
would match all the packages that have `acc` in the name

**Comment by sclevine** [comment]
I consider this out-of-scope for spec, which just organizes subtests and doesn't add any CLI flags to `go test`.

However, there are a number of ways to accomplish this using the standard testing package.
See: https://stackoverflow.com/questions/25965584/separating-unit-tests-and-integration-tests-in-go
